sudo: false
language: node_js
node_js:
  - 'stable'
  - '5'
  - '4'
  - '0.12'
  - '0.11'
  - '0.10'
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
